### ISSUE TITLE
Measurements need to run once every 2 minutes

### ISSUE THREAD

**Issue by ZekeMedley** [ZekeMedley/bencher#4]
Currenelty running every 5. Not sure if that is because iperf + measure takes three and we sleep 2 or if that is just me putting five instead of 2

**Comment by ZekeMedley** [comment]
- Could do throughput at different rate than pings so that they can test the SLAs

**Comment by ezekiiel** [comment]
Turns out that the times in this repo were different than the ones that I had on the cold / hot potato tests. Just needed to remember to change them for the direct connect tests as well.
